name: deployment-event-relays build and deploy

on:
  push: {}

env:
  image: ghcr.io/nais/deployment-event-relays

jobs:
  build:
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate version tags
      run: |
        echo "version=$(./version.sh)" >> $GITHUB_ENV
    - name: Build Docker image
      run: |
        docker build --tag ${image}:${version} .
    - name: Push Docker image to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${image}:${version}

  deploy:
    name: Deploy new version to NAIS
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate image environment variable
      run: |
        echo "version=$(./version.sh)" >> $GITHUB_ENV
    - name: Deploy to dev-gcp
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: .nais/nais.yaml
        VAR: image=${{ env.image }}:${{ env.version }},kafka_pool=nav-dev
