name: deployment-event-relays build and deploy
on:
  push:
    paths-ignore:
      - "*.md"
env:
  GOOGLE_REGISTRY: europe-north1-docker.pkg.dev

jobs:
  build:
    name: Build Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      version: ${{ steps.gen-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Build push and sign
        uses: nais/platform-build-push-sign@main # ratchet:exclude
        id: build-push-sign
        with:
          name: deployment-event-relays
          google_service_account: gh-deployment-event-relays
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true

  rollout:
    name: Rollout
    if: github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@v2 # ratchet:exclude
        with:
          chart: oci://${{ env.GOOGLE_REGISTRY }}/nais-io/nais/feature/deployd
          #version: ${{ needs.build.outputs.chart_version }}
